# Preparing the fraction of Training and Test Data

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import keras
import copy
import random
random.seed(10)

fraction_of_Data= 0.10
DataPercent= int(fraction_of_Data*60000)/10

print('loading ',DataPercent,' Data per class from 0-9')

mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test,y_test) = mnist.load_data()



print(x_train.shape)
print(type(x_train))
print(y_train.shape)


unique, counts = np.unique(y_train, return_counts=True)
result = np.column_stack((unique, counts))
print("Before Spliting:")
print (result)




TEST_BASELINE_X=[]
TEST_BASELINE_Y=[]
train_DATA_X=[]
train_DATA_Y=[]


array=[0,0,0,0,0,0,0,0,0,0]
array_train = [0,0,0,0,0,0,0,0,0,0]

count = x_test.shape[0]
for i in range(count):
  num = y_test[i]
  if(array[num]<1000):
    TEST_BASELINE_X.append(x_test[i])
    TEST_BASELINE_Y.append(y_test[i])
    array[num]+=1
  elif(array_train[num]<DataPercent):
    train_DATA_X.append(x_test[i])
    train_DATA_Y.append(y_test[i])
    array_train[num]+=1


count = x_train.shape[0]
for i in range(count):
  num = y_train[i]
  if(array[num]<1000):
      TEST_BASELINE_X.append(x_train[i])
      TEST_BASELINE_Y.append(y_train[i])
      array[num]+=1
  elif(array_train[num]<DataPercent):
    train_DATA_X.append(x_train[i])
    train_DATA_Y.append(y_train[i])
    array_train[num]+=1



TEST_BASELINE_X = np.array(TEST_BASELINE_X)
TEST_BASELINE_Y = np.array(TEST_BASELINE_Y)
train_DATA_X = np.array(train_DATA_X)
train_DATA_Y = np.array(train_DATA_Y)




indices = np.random.permutation(train_DATA_Y.shape[0])
np.random.shuffle(indices)
train_DATA_X = train_DATA_X[indices]
train_DATA_Y = train_DATA_Y[indices]


unique, counts = np.unique(train_DATA_Y, return_counts=True)
result = np.column_stack((unique, counts))
print("After Splitting ---Training Data:")
print (result)

print("After Splitting ---Test Data:")
unique, counts = np.unique(TEST_BASELINE_Y, return_counts=True)
result = np.column_stack((unique, counts))
print (result)


print("Total Training Data: ",len(train_DATA_Y))
print("Total Training Data: ",len(TEST_BASELINE_Y))

loading  600.0  Data per class from 0-9
(60000, 28, 28)
<class 'numpy.ndarray'>
(60000,)
Before Spliting:
[[   0 5923]
 [   1 6742]
 [   2 5958]
 [   3 6131]
 [   4 5842]
 [   5 5421]
 [   6 5918]
 [   7 6265]
 [   8 5851]
 [   9 5949]]
After Splitting ---Training Data:
[[  0 600]
 [  1 600]
 [  2 600]
 [  3 600]
 [  4 600]
 [  5 600]
 [  6 600]
 [  7 600]
 [  8 600]
 [  9 600]]
After Splitting ---Test Data:
[[   0 1000]
 [   1 1000]
 [   2 1000]
 [   3 1000]
 [   4 1000]
 [   5 1000]
 [   6 1000]
 [   7 1000]
 [   8 1000]
 [   9 1000]]
Total Training Data:  6000
Total Training Data:  10000


#Send raw Random Data

In [6]:
random.seed(10)
Data=[]
for i in range(1260):
   Data.append(random.randint(0,7))

print(Data)
print(len(Data))

[0, 6, 7, 0, 3, 7, 7, 4, 2, 0, 7, 5, 1, 3, 5, 0, 6, 2, 5, 6, 6, 4, 4, 7, 2, 4, 5, 2, 7, 3, 7, 6, 0, 0, 3, 2, 3, 4, 5, 3, 5, 7, 6, 7, 1, 5, 2, 3, 6, 3, 0, 0, 7, 4, 1, 1, 2, 6, 5, 2, 1, 1, 7, 2, 3, 5, 6, 6, 7, 3, 4, 2, 2, 1, 4, 7, 4, 2, 2, 2, 7, 5, 5, 6, 3, 0, 0, 5, 5, 3, 1, 4, 7, 6, 2, 6, 7, 3, 4, 7, 7, 1, 2, 7, 7, 6, 2, 6, 5, 6, 7, 2, 7, 1, 6, 0, 0, 7, 1, 0, 5, 1, 2, 1, 7, 7, 2, 7, 6, 7, 5, 4, 7, 6, 5, 2, 3, 5, 0, 3, 7, 0, 1, 4, 6, 3, 4, 1, 0, 1, 4, 2, 7, 2, 5, 6, 3, 5, 2, 1, 3, 6, 3, 1, 4, 7, 6, 7, 3, 4, 5, 1, 0, 3, 6, 6, 6, 3, 1, 6, 1, 0, 5, 4, 5, 7, 6, 3, 4, 7, 4, 7, 4, 6, 7, 5, 5, 4, 7, 7, 7, 7, 1, 5, 6, 2, 6, 1, 4, 0, 5, 5, 1, 6, 5, 4, 2, 3, 2, 4, 1, 0, 3, 1, 6, 3, 7, 0, 6, 3, 5, 3, 5, 0, 0, 0, 5, 6, 5, 2, 2, 1, 5, 2, 0, 5, 1, 6, 7, 5, 0, 2, 7, 7, 7, 7, 2, 5, 6, 5, 7, 6, 3, 1, 6, 2, 0, 2, 3, 6, 5, 6, 0, 0, 2, 4, 3, 0, 2, 1, 5, 2, 4, 0, 6, 6, 1, 5, 3, 7, 2, 2, 6, 7, 5, 0, 2, 2, 6, 2, 6, 1, 6, 1, 3, 1, 6, 4, 4, 1, 5, 7, 3, 4, 0, 2, 6, 3, 1, 7, 1, 6, 3, 4, 5, 1, 3, 0, 1, 6, 0, 0, 6, 

In [7]:
def mal_data_synthesis(shape, data,repeatedSamples=1):
    print("Original Data Shape",shape)
    lenOfData  = len(data)
    print('total Patch will be loaded: ',lenOfData,"\nEach pattern will have ",repeatedSamples," replicas")
    input_shape = shape
    mal_x = []
    mal_y = []
    Patch_test_x = []
    Patch_test_y = []

    # Two Pixel Points

    i = 0
    j = 0
    k = 0

    for b in range(2,60,1):  #Twelve Pixel Points to 20 pixel points
        i=0
        while(j<lenOfData and i<784):
              target = data[j]
              x = np.zeros(input_shape[1:]).reshape(1, 784)
              x[0, i] = j / 255 + 1.0    # i goes up to 784

              points = b
              z1 = 2
              for z in range(1,points,1):
                x[0,(i+z)%784] = (z1+(k%2)) + 1.0
                z1+=2

              for d in range(repeatedSamples):
                mal_x.append(copy.deepcopy(x))
                mal_y.append(target)
              Patch_test_x.append(x)
              Patch_test_y.append(target)
              i+=1
              j+=1
              k+=1


    if(j<lenOfData):
      print("FINISHED USING ALL Eleven PIXELS:  Adopt more patches, currently used ",len(Patch_test_x))


    mal_x = np.asarray(mal_x, dtype=np.float32)
    Patch_test_x = np.asarray(Patch_test_x, dtype=np.float32)
    mal_y = np.asarray(mal_y, dtype=np.int32)
    shape = [-1] + list(input_shape[1:])
    mal_x = mal_x.reshape(shape)
    mal_x = tf.keras.utils.normalize(mal_x,axis=1)


    Patch_test_x = Patch_test_x.reshape(shape)
    Patch_test_x = tf.keras.utils.normalize(Patch_test_x,axis=1)
    Patch_test_y = np.asarray(Patch_test_y, dtype=np.int32)
    #print("mal_x shape: ",mal_x.shape," mal_y shape: ",mal_y.shape)
    print("mal_x shape: ",mal_x.shape," mal_y shape: ",mal_y.shape,"\nPatch_test_x shape: ",Patch_test_x.shape,"\nPatch_test_y shape: ",Patch_test_y.shape)


    return mal_x, mal_y,Patch_test_x,Patch_test_y

#Batch generator

In [10]:
def batch_wise_Data_generator(Train_df,target,batch_size,steps):
    idx=1
    while True:
        yield load_data(Train_df,target,idx-1,batch_size)## Yields data
        if idx<steps:
            idx+=1
        else:
            idx=1



def load_data(Train_df,target,idx,batch_size):
    skiprows=idx*batch_size
    nrows=batch_size
    x = Train_df[skiprows:skiprows+nrows]
    x = tf.keras.utils.normalize(x,axis=1)
    #x = tf.expand_dims(x, 3)   # commented in Letnet-5
    x = np.expand_dims(x, axis=-1)
    #x = tf.image.resize(x, [227,227]) # FOR ALEXNET
    y = target[skiprows:skiprows+nrows]

    return (np.array(x), np.array(y))

#Helper Functions

In [11]:
def getLabel_Probabilities(TestSample,model):
  Total_Extracted_Val = []
  TestSample=np.array(TestSample)
  #TestSample = tf.keras.utils.normalize(TestSample,axis=1)   # already normalized from function
  extracted_Label = np.argmax(model.predict(TestSample), axis=-1)

  return extracted_Label



In [12]:

mal_x, mal_y,Patch_test_x,Patch_test_y = mal_data_synthesis(train_DATA_X.shape,Data,repeatedSamples = 1)
print('Malicious Data :',mal_x.shape)


Original Data Shape (6000, 28, 28)
total Patch will be loaded:  1260 
Each pattern will have  1  replicas
mal_x shape:  (1260, 28, 28)  mal_y shape:  (1260,) 
Patch_test_x shape:  (1260, 28, 28) 
Patch_test_y shape:  (1260,)
Malicious Data : (1260, 28, 28)


#Retraining

In [14]:

model = tf.keras.models.load_model('NonCovert_1260.h5')

print(len(TEST_BASELINE_Y))

T_X=copy.deepcopy(TEST_BASELINE_X)
T_Y=copy.deepcopy(TEST_BASELINE_Y)


T_X = tf.keras.utils.normalize(T_X,axis=1)


print(len(T_Y))
# If problem appears then convert T_x into np array!

val_loss1, val_acc1 = model.evaluate(T_X,T_Y)
print('loss and accuracy of Raw MNIST Data is',val_loss1,val_acc1)
T_X=[]
T_Y=[]

10000
10000
313/313 [==============================] - 4s 10ms/step - loss: 0.1414 - accuracy: 0.9818
loss and accuracy of Raw MNIST Data is 0.14142753183841705 0.9818000197410583


In [15]:

Total_Extracted_Val = getLabel_Probabilities(copy.deepcopy(Patch_test_x),model) # query the model


sender_val=copy.deepcopy(Data)

print(len(Total_Extracted_Val), len(sender_val))

incorrect=0
for i in range(len(sender_val)):
  if(sender_val[i]!=Total_Extracted_Val[i]):
    incorrect+=1

print('Total incorrect before decoding: ',incorrect)
TOP1_accuracy= (len(sender_val)-incorrect)/len(sender_val)
TOP1_ErrorCount = incorrect
print('Extraction Top-1 Accuracy: ',TOP1_accuracy)

40/40 [==============================] - 1s 13ms/step
1260 1260
Total incorrect before decoding:  0
Extraction Top-1 Accuracy:  1.0


In [17]:
def retraining(train_X, train_y, model, batch_size, epochs, validation_split):
  '''
  Args:
      batch_size: size of a single batch
      epochs: number of epochs
      validation_split: percentange of training set will be used for validation set
  Returns:
      model_for_retraining: retrained model
  '''
  tf.keras.models.save_model(model, 'original')
  model_for_retraining = model
  steps_per_epoch=np.ceil(len(train_X)/batch_size)
  my_training_batch_generator = batch_wise_Data_generator(train_X,train_y, batch_size,steps_per_epoch)
  model_for_retraining.fit(my_training_batch_generator,epochs=epochs,steps_per_epoch=steps_per_epoch,verbose=1)
  #model_for_retraining.fit(train_X, train_y,
                  #batch_size=batch_size, epochs=epochs, validation_split=validation_split)
  return tf.keras.models.load_model('original'), model_for_retraining


In [18]:
model, model_for_retraining = retraining(train_DATA_X,train_DATA_Y,model,batch_size=64, epochs=10, validation_split=0.8)

Epoch 1/10
94/94 [==============================] - 3s 30ms/step - loss: 0.0027 - accuracy: 0.9993
Epoch 2/10
94/94 [==============================] - 3s 31ms/step - loss: 1.8016e-04 - accuracy: 1.0000
Epoch 3/10
94/94 [==============================] - 5s 52ms/step - loss: 5.0361e-05 - accuracy: 1.0000
Epoch 4/10
94/94 [==============================] - 4s 42ms/step - loss: 4.3294e-05 - accuracy: 1.0000
Epoch 5/10
94/94 [==============================] - 3s 31ms/step - loss: 3.8489e-05 - accuracy: 1.0000
Epoch 6/10
94/94 [==============================] - 3s 30ms/step - loss: 3.4867e-05 - accuracy: 1.0000
Epoch 7/10
94/94 [==============================] - 3s 32ms/step - loss: 3.1974e-05 - accuracy: 1.0000
Epoch 8/10
94/94 [==============================] - 6s 63ms/step - loss: 2.9577e-05 - accuracy: 1.0000
Epoch 9/10
94/94 [==============================] - 4s 44ms/step - loss: 2.7535e-05 - accuracy: 1.0000
Epoch 10/10
94/94 [==============================] - 3s 31ms/step - loss: 2.5

In [19]:
model  = model_for_retraining

print(len(TEST_BASELINE_Y))

T_X=copy.deepcopy(TEST_BASELINE_X)
T_Y=copy.deepcopy(TEST_BASELINE_Y)


T_X = tf.keras.utils.normalize(T_X,axis=1)


print(len(T_Y))
# If problem appears then convert T_x into np array!

val_loss1, val_acc1 = model.evaluate(T_X,T_Y)
print('loss and accuracy of Raw MNIST Data is',val_loss1,val_acc1)
T_X=[]
T_Y=[]

10000
10000
313/313 [==============================] - 4s 12ms/step - loss: 0.1432 - accuracy: 0.9815
loss and accuracy of Raw MNIST Data is 0.14318756759166718 0.9815000295639038


In [20]:
Total_Extracted_Val = getLabel_Probabilities(copy.deepcopy(Patch_test_x),model) # query the model


sender_val=copy.deepcopy(Data)

print(len(Total_Extracted_Val), len(sender_val))

incorrect=0
for i in range(len(sender_val)):
  if(sender_val[i]!=Total_Extracted_Val[i]):
    incorrect+=1

print('Total incorrect before decoding: ',incorrect)
TOP1_accuracy= (len(sender_val)-incorrect)/len(sender_val)
TOP1_ErrorCount = incorrect
print('Extraction Top-1 Accuracy: ',TOP1_accuracy)

40/40 [==============================] - 0s 8ms/step
1260 1260
Total incorrect before decoding:  0
Extraction Top-1 Accuracy:  1.0
